// AUTOGENERATED FILE; see /go/src/github.com/docker/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "786b29d"
	VERSION   string = "1.7.1"

	IAMSTATIC string = "false"
	INITSHA1  string = "a455ebdac317271b38e5bf089e38f48629fe9119"
	INITPATH  string = ""
)
