// AUTOGENERATED FILE; see /home/hekra/Q1/docker/hack/make/.go-autogen
package dockerversion

var (
	GITCOMMIT string = "54a1175"
	VERSION   string = "1.7.1"

	IAMSTATIC string = "true"
	INITSHA1  string = ""
	INITPATH  string = ""
)
