.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""

.SH NAME
.PP
docker\-commit \- Create a new image from a container's changes

.SH SYNOPSIS
.PP
\fBdocker commit\fP
[\fB\-a\fP|\fB\-\-author\fP[=\fIAUTHOR\fP]]
[\fB\-\-help\fP]
[\fB\-c\fP|\fB\-\-change\fP[= []\fB]]
[\fP\-m\fB|\fP\-\-message\fB[=\fIMESSAGE\fP]]
[\fP\-p\fB|\fP\-\-pause*\fI[=*true\fP]]
CONTAINER [REPOSITORY[:TAG]]

.SH DESCRIPTION
.PP
Using an existing container's name or ID you can create a new image.

.SH OPTIONS
.PP
\fB\-a\fP, \fB\-\-author\fP=""
   Author (e.g., "John Hannibal Smith 
\[la]hannibal@a-team.com\[ra]")

.PP
\fB\-c\fP , \fB\-\-change\fP=[]
   Apply specified Dockerfile instructions while committing the image
   Supported Dockerfile instructions: \fB\fCCMD\fR|\fB\fCENTRYPOINT\fR|\fB\fCENV\fR|\fB\fCEXPOSE\fR|\fB\fCONBUILD\fR|\fB\fCUSER\fR|\fB\fCVOLUME\fR|\fB\fCWORKDIR\fR

.PP
\fB\-\-help\fP
  Print usage statement

.PP
\fB\-m\fP, \fB\-\-message\fP=""
   Commit message

.PP
\fB\-p\fP, \fB\-\-pause\fP=\fItrue\fP|\fIfalse\fP
   Pause container during commit. The default is \fItrue\fP.

.SH EXAMPLES.SH Creating a new image from an existing container
.PP
An existing Fedora based container has had Apache installed while running
in interactive mode with the bash shell. Apache is also running. To
create a new image run \fB\fCdocker ps\fR to find the container's ID and then run:

.PP
.RS

.nf
# docker commit \-m="Added Apache to Fedora base image" \\
  \-a="A D Ministrator" 98bd7fc99854 fedora/fedora\_httpd:20

.fi
.RE
.SH Apply specified Dockerfile instructions while committing the image
.PP
If an existing container was created without the DEBUG environment
variable set to "true", you can create a new image based on that
container by first getting the container's ID with \fB\fCdocker ps\fR and
then running:

.PP
.RS

.nf
# docker commit \-c="ENV DEBUG true" 98bd7fc99854 debug\-image

.fi
.RE

.SH HISTORY
.PP
April 2014, Originally compiled by William Henry (whenry at redhat dot com)
based on docker.com source material and in
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
July 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
Oct 2014, updated by Daniel, Dao Quang Minh 
