.TH "DOCKER" "1" " Docker User Manuals" "Docker Community" "JUNE 2014"  ""

.SH NAME
.PP
docker\-version \- Show the Docker version information.

.SH SYNOPSIS
.PP
\fBdocker version\fP

.SH OPTIONS
.PP
There are no available options.

.SH HISTORY
.PP
June 2014, updated by Sven Dowideit 
\[la]SvenDowideit@home.org.au\[ra]
